# Goodix Touchscreen Makefile
# This Makefile is only for tempory compiling use
# Use xxxproject/Makefile-release when release driver
#
# core layer

obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_ts_core.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_cfg_bin.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_ts_test.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_gtx8_update.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_ts_gesture.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_F9S)		 += goodix_ts_tools.o
